- README.md
> doc: Add devops basic reference to README.md

- projects/dockerize-python-application/demo_project.sh
> fix curl 52 issue :bug:

- .github/workflows/verify-docker-image.yml
- .github/workflows/verify-nginx-static-website-local.yml
- README.md
- projects/nginx-static-website-local/Dockerfile
- projects/nginx-static-website-local/README.md
- projects/nginx-static-website-local/demo_project.sh
- projects/nginx-static-website-local/index.html
- projects/nginx-static-website-local/nginx.conf
> Add project03 nginx-static-website-local

- .github/workflows/nodejs-cicd-pipeline.yml
- README.md
- projects/nodejs-cicd-pipeline/README.md
> ci: running project04 CI on push event to main

- README.md
doc: improve repo introduction
> doc: improve repo introduction

- README.md
- projects/aws-tree-tiers-web/README.md
project: add projects/aws-tree-tiers-web/
> project: add projects/aws-tree-tiers-web

- README.md
In https://github.com/tungbq/devops-project/blob/main/README.md#check-out-projects Changed from
Check out [projects](https://github.com/tungbq/devops-project/blob/main/projects) to
Check out [projects](https://github.com/tungbq/devops-project/blob/main/projects) list below
> Content Improvement in README

- README.md
doc: add upcoming projects link
> doc: add upcoming projects link

- .github/dependabot.yml
> ci: add terraform dependabot for projects/create-k8s-cluster-aws-ec2

- .github/workflows/terraform-runner.yml
> ci: add new terraform workflow with manual trigger event

- planning/PROJECT_IDEA.md
> doc: Create PROJECT_IDEA.md

- README.md
> badge: adding repo stars ⭐ 

- README.md
aks: add new project AKS to table
Related #88
> aks: add new project AKS to table

- projects/terraform-aks-cluster/README.md
aks: doc improvement (project 08)
> aks: doc improvement

- README.md
> project09: adjust title

- README.md
- docs/project_template.md
- projects/aks-istio-application/README.md
- projects/aws-tree-tiers-web/README.md
- projects/create-k8s-cluster-aws-ec2/README.md
- projects/dockerize-python-application/README.md
- projects/nginx-static-website-local/README.md
- projects/nodejs-cicd-pipeline/README.md
doc: improve project documentation
> doc: improve project documentation

- projects/aks-istio-application/README.md
> doc: fix url broken

- projects/aks-istio-application/README.md
> doc: Istio improvement

- README.md
> doc: update project content table

- README.md
- projects/aks-nginx-with-istio/README.md
doc: minor guide updates
Related #98
> doc: minor guide updates

- projects/aks-istio-application/helm_manifests/istio_prom_values.yaml
- projects/aks-nginx-with-istio/README.md
> doc: adjust link and type

- README.md
Add jenkins-on-k8s project from K8sHub
See: https://github.com/tungbq/K8sHub/tree/main/hands-on/jenkins-on-k8s
> Add jenkins-on-k8s project from K8sHub

- README.md
**Description**:
**Related issue(s)**:
Fixes #
**Notes for reviewer**:
**Checklist**
> Add trio project info

- README.md
**Description**:
**Related issue(s)**:
Fixes #
**Notes for reviewer**:
**Checklist**
> Adjust trio message

- README.md
**Description**:
**Related issue(s)**:
Fixes #
**Notes for reviewer**:
**Checklist**
> Using  ↔️ icon

- README.md
Made the DevOps basics link bold in the README for better emphasis.
> Update readme bold link

- README.md
- planning/PROJECT_IDEA.md
> Add aws architecture link
